name: Lint

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npm run lint:styles
